### ISSUE TITLE
I also get the apt warning, even on adding `python-apt` myself.

### ISSUE THREAD

**Issue by ajit-1234** [atc0005/ansible-role-lxd-testenv#53]
I also get the apt warning, even on adding `python-apt` myself.

_Originally posted by @J7mbo in https://github.com/atc0005/ansible-role-lxd-testenv/issues/50#issuecomment-624118208_

**Comment by atc0005** [comment]
Hi @ajit-1234,

Is that when using this Ansible role or with other Ansible roles/playbooks?

**Comment by ajit-1234** [comment]
Yes while installing tomcat also

**Comment by ajit-1234** [comment]
Please give answer soon

**Comment by atc0005** [comment]
> @ajit-1234: Yes while installing tomcat also

I'm not sure I follow. What version of this Ansible role are you using? I recently merged #52 which seemed to fix the problem with this role. Version 1.3.1 contains that change.

I recommend running `ansible-galaxy role list` to confirm that you have version 1.3.1 of this role installed before regenerating LXD containers in your test LXD environment.

If you're not using this role, the issue you are encountering may be related to another problem. These resources may be of help to you:

- https://github.com/ansible/ansible/issues/14468
- https://stackoverflow.com/questions/51622712/ansible-requires-python-apt-but-its-already-installed/51623235

**Comment by atc0005** [comment]
Closing based on no response from my last post. I hope it was helpful and it was sufficient to lead you in the right direction.

If this report is an issue with this specific Ansible role *and* the problem persists, please respond and reopen. Thanks.
